#!/usr/bin/env bash

for i in $(seq -f "%03g" 0 999); do
  rm -f ornithischia_${i}.gas
  cp ornithischia_base.gas ornithischia_${i}.gas
  echo "
analyses:

ornithischia_${i} {
  searchMethod geneticAlgorithm
  gaParams nni 50% 32 1000000000 500000
  bsParams 0
}" >>ornithischia_${i}.gas
done
