#!/usr/bin/env bash

for i in $(seq -f "%03g" 0 999); do
  rm -f hexapoda_${i}.gas
  cp hexapoda_base.gas hexapoda_${i}.gas
  echo "
analyses:

hexapoda_${i} {
  searchMethod geneticAlgorithm
  gaParams nni 50% 32 1000000 50000
  bsParams 0
}" >>hexapoda_${i}.gas
done
